# Generated by Django 6.0 on 2025-12-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrityprofile',
            name='chunk_entropies',
            field=models.JSONField(default=list),
        ),
    ]
