# Generated by Django 6.0 on 2025-12-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_integrityprofile_chunk_entropies'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrityprofile',
            name='file_header',
            field=models.CharField(default='', max_length=64),
        ),
    ]
